# Generated by Django 5.2.3 on 2025-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
