# Generated by Django 5.2.3 on 2025-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('subject_name', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=60, unique=True)),
                ('subject_id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
