# Generated by Django 5.2.3 on 2025-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_courses_subject_id'),
        ('student', '0003_grade_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('maths', 'Maths'), ('hindi', 'Hindi'), ('english', 'English'), ('social_science', 'Social Science'), ('general_science', 'General Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('computer_science', 'Computer Science'), ('biology', 'Biology'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('economics', 'Economics'), ('history', 'History'), ('political_science', 'Political Science'), ('painting', 'Painting')], max_length=100)),
                ('grades', models.ManyToManyField(to='student.grade')),
                ('streams', models.ManyToManyField(blank=True, to='student.stream')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
