# Generated by Django 5.2.3 on 2025-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('student', '0003_grade_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculties',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='subject',
        ),
        migrations.AddField(
            model_name='faculties',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculties',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculties',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculties',
            name='grades',
            field=models.ManyToManyField(help_text='Select grades this faculty teaches', to='student.grade'),
        ),
        migrations.AddField(
            model_name='faculties',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='faculties',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
