# Generated by Django 5.2.3 on 2025-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('rollnumber', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
