from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from student.student_crud_models import StudentMarks, Student, Grade
from faculty.models import faculties
from django.conf import settings
from django.core.mail import EmailMessage
from django.http import FileResponse
import os
from io import BytesIO
from django.urls import reverse
from django.http import HttpResponse
import csv
import io


def is_faculty(user):
    return user.is_staff and not user.is_superuser


@login_required
@user_passes_test(is_faculty)
def marks_list(request):
    """View marks added by the current faculty"""
    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')
    
    marks = StudentMarks.objects.filter(faculty=faculty).select_related('student')
    context = {
        'marks': marks,
        'faculty': faculty,
    }
    return render(request, 'student/marks_list.html', context)


def _generate_marks_pdf(mark_record):
    """Generate a PDF for the given StudentMarks record and save it under MEDIA_ROOT/marksheets.
    Returns the absolute file path of the saved PDF. If ReportLab is not available, returns None.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except Exception:
        return None

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    left = 40
    y = height - 50
    c.setFont('Helvetica-Bold', 16)
    c.drawString(left, y, 'Marks Report')
    y -= 30

    c.setFont('Helvetica', 11)
    # Student details
    student = mark_record.student
    faculty = mark_record.faculty
    c.drawString(left, y, f"Student: {getattr(student, 'name', '')}")
    y -= 18
    c.drawString(left, y, f"Roll Number: {getattr(student, 'roll_number', '')}")
    y -= 18
    grade_display = student.grade.get_grade_display() if getattr(student, 'grade', None) else ''
    c.drawString(left, y, f"Grade: {grade_display}")
    y -= 24

    # Mark details
    c.drawString(left, y, f"Subject: {mark_record.subject}")
    y -= 18
    c.drawString(left, y, f"Exam Type: {mark_record.get_exam_type_display()}")
    y -= 18
    c.drawString(left, y, f"Marks Obtained: {mark_record.marks_obtained} / {mark_record.total_marks}")
    y -= 18
    c.drawString(left, y, f"Percentage: {mark_record.percentage:.2f}%")
    y -= 30

    c.drawString(left, y, f"Recorded By: {getattr(faculty, 'name', '')}")
    y -= 18
    c.drawString(left, y, f"Recorded On: {mark_record.date_recorded.strftime('%Y-%m-%d %H:%M')}")
    y -= 30

    c.setFont('Helvetica-Oblique', 9)
    c.drawString(left, y, 'Generated by Student Management System')

    c.showPage()
    c.save()

    pdf_data = buffer.getvalue()
    buffer.close()

    # Ensure MEDIA_ROOT exists
    media_root = getattr(settings, 'MEDIA_ROOT', None)
    if not media_root:
        # fallback to project base dir
        media_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..', 'media')
    marks_dir = os.path.join(media_root, 'marksheets')
    os.makedirs(marks_dir, exist_ok=True)
    file_name = f"mark_{mark_record.id}.pdf"
    file_path = os.path.join(marks_dir, file_name)
    with open(file_path, 'wb') as f:
        f.write(pdf_data)

    return file_path


@login_required
@user_passes_test(is_faculty)
def marks_add(request):
    """Faculty adds marks for students in their assigned grades"""
    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')
    
    # Get all grades assigned to this faculty
    assigned_grades = faculty.grades.all()

    # Populate the dropdown from the Student model (all students).
    # Faculty may be assigned specific grades, but show all students to make selection easier.
    students = Student.objects.all().order_by('name')
    fallback_mode = False

    if request.method == 'POST':
        student_id = request.POST.get('student')
        subject = request.POST.get('subject')
        exam_type = request.POST.get('exam_type')
        marks_obtained = request.POST.get('marks_obtained')
        total_marks = request.POST.get('total_marks', 100)

        try:
            marks_obtained = float(marks_obtained)
            total_marks = float(total_marks)
        except ValueError:
            messages.error(request, 'Marks must be numeric values.')
            return redirect('marks_add')

        if marks_obtained < 0 or total_marks <= 0 or marks_obtained > total_marks:
            messages.error(request, 'Invalid marks. Please check values.')
            return redirect('marks_add')


        try:
            student = Student.objects.get(id=student_id)

            # If student not in faculty's assigned grades, warn but allow save so faculty can still record marks.
            if assigned_grades.exists() and (student.grade not in assigned_grades):
                messages.warning(request, 'Student is outside your assigned grades — saving marks anyway.')

            # Create or update marks
            mark_record, created = StudentMarks.objects.update_or_create(
                student=student,
                subject=subject,
                exam_type=exam_type,
                defaults={
                    'marks_obtained': marks_obtained,
                    'total_marks': total_marks,
                    'faculty': faculty,
                }
            )

            if created:
                messages.success(request, f'Marks added for {student.name} in {subject}.')
            else:
                messages.success(request, f'Marks updated for {student.name} in {subject}.')

            # Generate marksheet PDF and email it to the student if possible
            pdf_path = None
            try:
                pdf_path = _generate_marks_pdf(mark_record)
            except Exception as e:
                messages.error(request, f'Error generating PDF: {e}')

            student_email = getattr(student, 'email', None)
            if pdf_path and student_email:
                try:
                    email = EmailMessage(
                        subject=f"Marks Report - {mark_record.subject} ({mark_record.get_exam_type_display()})",
                        body=f"Dear {getattr(student, 'name', 'Student')},\n\nPlease find attached the marks report for {mark_record.subject}.\n\nRegards,\n{getattr(faculty, 'name', '')}",
                        from_email=getattr(settings, 'DEFAULT_FROM_EMAIL', None),
                        to=[student_email],
                    )
                    with open(pdf_path, 'rb') as f:
                        email.attach(os.path.basename(pdf_path), f.read(), 'application/pdf')
                    email.send(fail_silently=False)
                    messages.success(request, 'PDF generated and emailed to the student.')
                except Exception as e:
                    messages.error(request, f'Could not send email: {e}')
            else:
                # Inform if PDF not generated or no email
                if not pdf_path:
                    messages.warning(request, 'PDF not generated (ReportLab may be missing).')
                if not student_email:
                    messages.warning(request, 'Student has no email configured; cannot send PDF.')

            # If PDF exists, redirect back to the add form with a download flag so JS can open it
            if pdf_path and os.path.exists(pdf_path):
                return redirect(f"{reverse('marks_add')}?download={mark_record.id}")

            return redirect('marks_list')

        except Student.DoesNotExist:
            messages.error(request, 'Student not found.')
            return redirect('marks_add')
    
    # students already set to all Student objects above (so no further fallback logic needed)

    # Build a safe list of student options (id, display_name, roll, grade_display)
    student_options = []
    from student.models import registrationstudent
    for s in students:
        # Prefer the Student.name field. If missing, try to look up by email in registrationstudent
        display_name = getattr(s, 'name', '') or ''
        if not display_name:
            try:
                reg = registrationstudent.objects.get(email=s.email)
                display_name = f"{reg.first_name} {reg.last_name}".strip()
            except registrationstudent.DoesNotExist:
                display_name = s.email or (s.roll_number if hasattr(s, 'roll_number') else str(s.id))

        roll = getattr(s, 'roll_number', '')
        grade_display = s.grade.get_grade_display() if getattr(s, 'grade', None) else ''
        student_options.append({
            'id': s.id,
            'name': display_name,
            'roll': roll,
            'grade': grade_display,
        })

    context = {
        'students': students,
        'student_options': student_options,
        'faculty': faculty,
        'exam_types': StudentMarks._meta.get_field('exam_type').choices,
    }
    return render(request, 'student/marks_form.html', context)


@login_required
@user_passes_test(is_faculty)
def marks_edit(request, pk):
    """Edit marks"""
    mark = get_object_or_404(StudentMarks, id=pk)
    
    # Verify that the mark belongs to the current faculty
    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')
    
    if mark.faculty != faculty:
        messages.error(request, 'You do not have permission to edit this record.')
        return redirect('marks_list')
    
    if request.method == 'POST':
        try:
            mark.marks_obtained = float(request.POST.get('marks_obtained'))
            mark.total_marks = float(request.POST.get('total_marks', mark.total_marks))
            mark.exam_type = request.POST.get('exam_type')
            
            if mark.marks_obtained < 0 or mark.total_marks <= 0 or mark.marks_obtained > mark.total_marks:
                messages.error(request, 'Invalid marks. Please check values.')
                return redirect('marks_edit', pk=pk)
            
            mark.save()
            messages.success(request, 'Marks updated successfully.')
            return redirect('marks_list')
        
        except ValueError:
            messages.error(request, 'Marks must be numeric values.')
            return redirect('marks_edit', pk=pk)
    
    context = {
        'mark': mark,
        'exam_types': StudentMarks._meta.get_field('exam_type').choices,
    }
    return render(request, 'student/marks_edit.html', context)


@login_required
@user_passes_test(is_faculty)
def marks_delete(request, pk):
    """Delete marks"""
    mark = get_object_or_404(StudentMarks, id=pk)
    
    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')
    
    if mark.faculty != faculty:
        messages.error(request, 'You do not have permission to delete this record.')
        return redirect('marks_list')
    
    if request.method == 'POST':
        student_name = mark.student.name
        mark.delete()
        messages.success(request, f'Marks deleted for {student_name}.')
        return redirect('marks_list')
    
    context = {'mark': mark}
    return render(request, 'student/marks_confirm_delete.html', context)


@login_required
@user_passes_test(is_faculty)
def marks_download(request, pk):
    """Return the generated marksheet PDF for the given mark record if it exists."""
    mark = get_object_or_404(StudentMarks, id=pk)
    # Build file path
    media_root = getattr(settings, 'MEDIA_ROOT', None)
    if not media_root:
        media_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..', 'media')
    file_path = os.path.join(media_root, 'marksheets', f'mark_{mark.id}.pdf')
    # If PDF missing, attempt to generate it now
    if not os.path.exists(file_path):
        try:
            generated = _generate_marks_pdf(mark)
            if generated:
                file_path = generated
            else:
                messages.error(request, 'Marksheet not found and could not be generated (ReportLab missing).')
                return redirect('marks_list')
        except Exception as e:
            messages.error(request, f'Error generating marksheet: {e}')
            return redirect('marks_list')

    try:
        return FileResponse(open(file_path, 'rb'), as_attachment=True, filename=os.path.basename(file_path))
    except Exception as e:
        messages.error(request, f'Could not open marksheet file: {e}')
        return redirect('marks_list')


@login_required
@user_passes_test(is_faculty)
def marks_email(request, pk):
    """Generate the PDF (if needed) and email it to the student for the given mark record."""
    mark = get_object_or_404(StudentMarks, id=pk)

    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')

    if mark.faculty != faculty:
        messages.error(request, 'You do not have permission to email this record.')
        return redirect('marks_list')

    # Send a plain-text email containing the marks details (no attachment)
    student_email = getattr(mark.student, 'email', None)
    if not student_email:
        messages.error(request, 'Student has no email configured.')
        return redirect('marks_list')

    # Build plain-text email body with the teacher-entered details
    student_name = getattr(mark.student, 'name', 'Student')
    roll = getattr(mark.student, 'roll_number', '')
    grade_display = mark.student.grade.get_grade_display() if getattr(mark.student, 'grade', None) else ''
    faculty_name = getattr(faculty, 'name', '')
    recorded_on = mark.date_recorded.strftime('%Y-%m-%d %H:%M') if getattr(mark, 'date_recorded', None) else ''
    body_lines = [
        f"Dear {student_name},",
        "",
        f"This is the marks report entered by your teacher:",
        "",
        f"Student: {student_name}",
        f"Roll Number: {roll}",
        f"Grade: {grade_display}",
        f"Subject: {mark.subject}",
        f"Exam Type: {mark.get_exam_type_display()}",
        f"Marks Obtained: {mark.marks_obtained} / {mark.total_marks}",
        f"Percentage: {mark.percentage:.2f}%",
        f"Recorded By: {faculty_name}",
        f"Recorded On: {recorded_on}",
        "",
        "If you have any questions, please contact your teacher.",
        "",
        f"Regards,",
        f"{faculty_name}",
    ]

    body = "\n".join(body_lines)

    try:
        email = EmailMessage(
            subject=f"Marks Report - {mark.subject} ({mark.get_exam_type_display()})",
            body=body,
            from_email=getattr(settings, 'DEFAULT_FROM_EMAIL', None),
            to=[student_email],
        )
        email.send(fail_silently=False)
        messages.success(request, 'Marks details emailed to the student successfully.')
    except Exception as e:
        messages.error(request, f'Could not send email: {e}')

    return redirect('marks_list')


@login_required
@user_passes_test(is_faculty)
def test_email(request):
    """Diagnostic endpoint: send a small test email to the address passed as ?to=.
    Returns plain text status to help debug email configuration.
    Access: faculty users only.
    """
    to_addr = request.GET.get('to')
    if not to_addr:
        return HttpResponse('Provide ?to=student@example.com', status=400)

    subject = 'Test Email from Student Management System'
    body = 'This is a test email sent from the Student Management System to verify SMTP configuration.'
    try:
        msg = EmailMessage(subject=subject, body=body, from_email=getattr(settings, 'DEFAULT_FROM_EMAIL', None), to=[to_addr])
        msg.send(fail_silently=False)
        return HttpResponse(f'Test email sent to {to_addr} (check recipient inbox and server logs).')
    except Exception as e:
        return HttpResponse(f'Error sending test email: {e}', status=500)


@login_required
@user_passes_test(is_faculty)
def marks_upload(request):
    """Allow faculty to upload a CSV to bulk create/update StudentMarks.

    Expected CSV columns (headers recommended):
      - roll_number (preferred) OR student_id OR email
      - subject
      - exam_type  (one of StudentMarks.EXAM_TYPE_CHOICES values: midterm, final, quiz, assignment, project)
      - marks_obtained
      - total_marks (optional, defaults to 100)

    The view will attempt to locate students by roll_number first, then by id, then by email.
    A summary of processed/created/updated/failed rows is shown via messages.
    """
    try:
        faculty = faculties.objects.get(email=request.user.email)
    except faculties.DoesNotExist:
        messages.error(request, 'Faculty profile not found.')
        return redirect('faculty_welcome')

    if request.method == 'POST':
        csv_file = request.FILES.get('csv_file')
        if not csv_file:
            messages.error(request, 'No file uploaded. Please choose a CSV file.')
            return redirect('marks_upload')

        # Read and decode file safely
        try:
            decoded = csv_file.read().decode('utf-8')
        except Exception:
            try:
                decoded = csv_file.read().decode('latin-1')
            except Exception:
                messages.error(request, 'Could not decode uploaded file. Ensure it is a valid CSV (UTF-8 or Latin-1).')
                return redirect('marks_upload')

        reader = csv.DictReader(io.StringIO(decoded))
        if reader.fieldnames is None:
            messages.error(request, 'CSV appears empty or malformed. Ensure it has a header row.')
            return redirect('marks_upload')

        # Normalize expected header names
        processed = 0
        created = 0
        updated = 0
        failed = []

        # Acceptable exam_type values
        valid_exam_types = {k for k, _ in StudentMarks._meta.get_field('exam_type').choices}

        for i, row in enumerate(reader, start=2):
            processed += 1
            # Trim keys & values
            row = {k.strip(): (v.strip() if isinstance(v, str) else v) for k, v in row.items() if k}

            # Identify student
            student = None
            roll = row.get('roll_number') or row.get('roll') or row.get('student_roll')
            sid = row.get('student_id') or row.get('id')
            email = row.get('email')

            try:
                if roll:
                    student = Student.objects.get(roll_number=roll)
                elif sid:
                    student = Student.objects.get(id=int(sid))
                elif email:
                    student = Student.objects.get(email=email)
                else:
                    raise Student.DoesNotExist('No identifier provided')
            except Exception as e:
                failed.append(f'Row {i}: Student not found ({e})')
                continue

            subject = row.get('subject')
            exam_type = row.get('exam_type')
            marks_obtained = row.get('marks_obtained')
            total_marks = row.get('total_marks') or row.get('max_marks') or '100'

            if not subject:
                failed.append(f'Row {i}: Missing subject')
                continue

            # Normalize exam_type: if human label provided, try to map to key
            if exam_type and exam_type not in valid_exam_types:
                # try lowercase mapping
                exam_type_try = exam_type.strip().lower()
                # map common words
                mapping = {
                    'mid': 'midterm', 'mid-term': 'midterm', 'midterm': 'midterm',
                    'final': 'final', 'quiz': 'quiz', 'assignment': 'assignment', 'project': 'project'
                }
                exam_type = mapping.get(exam_type_try, exam_type_try if exam_type_try in valid_exam_types else None)

            if not exam_type:
                failed.append(f'Row {i}: Invalid or missing exam_type')
                continue

            try:
                marks_obtained = float(marks_obtained)
                total_marks = float(total_marks)
            except Exception:
                failed.append(f'Row {i}: marks_obtained/total_marks must be numeric')
                continue

            if marks_obtained < 0 or total_marks <= 0 or marks_obtained > total_marks:
                failed.append(f'Row {i}: Invalid marks range')
                continue

            # Create or update
            try:
                mark_obj, was_created = StudentMarks.objects.update_or_create(
                    student=student,
                    subject=subject,
                    exam_type=exam_type,
                    defaults={
                        'marks_obtained': marks_obtained,
                        'total_marks': total_marks,
                        'faculty': faculty,
                    }
                )
                if was_created:
                    created += 1
                else:
                    updated += 1
            except Exception as e:
                failed.append(f'Row {i}: DB error: {e}')
                continue

        # Build summary
        summary_lines = [f'Processed: {processed}', f'Created: {created}', f'Updated: {updated}']
        if failed:
            messages.error(request, 'Some rows failed to import. See details in server log and messages.')
            # Attach a short list to messages (limited)
            for msg in failed[:10]:
                messages.error(request, msg)
            if len(failed) > 10:
                messages.error(request, f'And {len(failed)-10} more errors...')
        else:
            messages.success(request, 'CSV import completed successfully.')

        for line in summary_lines:
            messages.info(request, line)

        return redirect('marks_list')

    # GET -> show upload form and instructions
    context = {
        'faculty': faculty,
        'exam_types': StudentMarks._meta.get_field('exam_type').choices,
    }
    return render(request, 'student/marks_upload.html', context)
