# Generated by Django 5.2.3 on 2025-11-13 11:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade'), (9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], unique=True)),
            ],
        ),
        migrations.RunPython(
            # create Grade rows 1..12 so existing Student rows can point to a valid grade
            lambda apps, schema_editor: apps.get_model('student', 'Grade').objects.bulk_create([
                apps.get_model('student', 'Grade')(grade=i) for i in range(1, 13)
            ])
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'division', 'name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rollnumber',
            new_name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 13, 11, 27, 46, 511779, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(help_text='e.g., A, B, C', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.grade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=50, unique=True)),
                ('grades', models.ManyToManyField(limit_choices_to={'grade__gte': 11}, to='student.grade')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.stream'),
        ),
    ]
