# Generated by Django 5.2.3 on 2025-11-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_attendance_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstudent',
            name='course',
            field=models.CharField(blank=True, choices=[('bscit', 'BScIT'), ('bca', 'BCA'), ('msccs', 'MScCS'), ('mca', 'MCA')], default='bca', max_length=5, null=True),
        ),
    ]
