# Generated by Django 5.2.3 on 2025-11-27 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculties_options_remove_faculties_subject_and_more'),
        ('student', '0006_alter_registrationstudent_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term'), ('final', 'Final'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project')], max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField(default=100)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculties')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
    ]
